In [1]:
import numpy as np

In [2]:
# Numpy의 차원
"""
1차원 축(행) : axis 0 => Vector
2차원 축(열) : axis 1 => Matrix
3차원 축(채널) : axis 2 => Tensor(3차원 이상)
"""

'\n1차원 축(행) : axis 0 => Vector\n2차원 축(열) : axis 1 => Matrix\n3차원 축(채널) : axis 2 => Tensor(3차원 이상)\n'

In [5]:
list_data = [1, 2, 3]
array = np.array(list_data)
print(array.size)tents
print(array.dtype)
print(array[2])

3
int32
3


In [17]:
# Numpy배열 초기화하기
# 0부터 3까지의 배열
array1 = np.arange(4) # [0, 1, 2, 3]
print(array1)
# 배열 내의 모든 원소 0
# 배열의 shape과 원소의 type을 지정할 수 있다
array2 = np.zeros((4, 4), dtype=float) # 4x4 matrix
print(array2)
# 배열 내의 모든 원소 1
array3 = np.ones((3, ), dtype=str) # 1차원 vector (1x3 matrix와 다름)
print(array3)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
['1' '1' '1']


In [8]:
# 배열 내 원소 랜덤하게 초기화
array4 = np.random.randint(0, 10, (3, 3))
print(array4)

# 평균이 0이고, 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.randn(3, 3)
print(array5)

[[4 0 4]
 [9 3 8]
 [5 7 1]]
[[ 0.53950883  0.56300489  0.3826164 ]
 [-1.27402169 -0.42066608 -0.55664484]
 [-1.7450106  -0.99145344  1.56455829]]


In [12]:
# 가로축으로 배열 합치기
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2])
print(array3)

[1 2 3 4 5 6]


In [13]:
# 넘파이 배열 형태 바꾸기 reshape()
array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape(2, 2)
print(array2)

[[1 2]
 [3 4]]


In [19]:
# 세로축으로 배열 합치기
array1 = np.arange(4).reshape(1, 4) # 2차원 배열 1x4형태로 바꿔주기, np.arange(4)와는 엄연히 다른 형태이다
array2 = np.arange(8).reshape(2, 4) # 2차원 배열 2x4형태로 바꿔주기
print(array1)
print(array2)

array3 = np.concatenate([array1, array2], axis = 0)
print(array3)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]
